(require 'tqcov)
(when (< max-lisp-eval-depth 1000)
  (setq max-lisp-eval-depth 1000))

(defun tq-cov-test-setup (data-file)
  (setq dir (file-name-directory (buffer-file-name (current-buffer))))
  (tq-cov-create-stats-buffer (concat dir data-file)))

(expectations
   (desc "quoted list")
   (expect '(3 5)
     '(3 5))
   (expect '((3 5) (8 12))
     '((3 5) (8 12)))

   (desc "alist learning")
   (expect '("foo" . "bar")
     (setq words '(("hoge" . "fuga") ("foo" . "bar") ("toto" . "titi")))
     (assoc "foo" words)
     )
   (expect nil
     (setq words '(("hoge" . "fuga") ("foo" . "bar") ("toto" . "titi")))
     (assoc "BOO" words)
     )
   (expect '("hoge")
     (setq words '(("hoge")))
     (assoc "hoge" words)
     )
   (expect nil
     (setq words '(("hoge")))
     (cdr (assoc "hoge" words))
     )
   (expect '("fuga" "piyo" "moge")
     (setq words '(("hoge" "fuga" "piyo" "moge")))
     (cdr (assoc "hoge" words))
     )

   (desc "file contents loading")
   (expect 5
     (setq dir (file-name-directory (buffer-file-name (current-buffer))))
     (with-current-buffer (get-buffer-create "*tqcov-stats.csv*")
       (erase-buffer)
       (insert-file-contents (concat dir "coverage_stats.csv"))
       (count-lines (point-min) (point-max))))

   (desc "csv-forward-field")
   (expect 1
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (csv-forward-field 0)
       (point)
       ))
   (expect 21
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (csv-forward-field 1)
       (point)
       ))
   (expect 23
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (csv-forward-field 2)
       (point)
       ))
   (expect 25
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (csv-forward-field 3)
       (point)
       ))
   (expect 46
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (csv-forward-field 4)
       (point)
       ))

   (desc "tq-csv-current-field-to-string")
   (expect "/path/to/app/init.js"
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (tq-csv-current-field-to-string)))

   (desc "tq-csv-next-field-to-string")
   (expect 1
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (string-to-number (tq-csv-next-field-to-string))))
   (expect 2
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (tq-csv-next-field-to-string)
       (string-to-number (tq-csv-next-field-to-string))))

   (desc "csv-lines-to-list")
   (expect '("/path/to/app/init.js" 1 2)
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (tq-csv-line-to-list)))
   (expect '("/path/to/app/init.js" 3 1)
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (tq-csv-line-to-list)
       (forward-line)
       (tq-csv-line-to-list)))

   (desc "tq-cov-parse-buffer")
   (expect '("/path/to/app/init.js" 6 4)
     (with-current-buffer (tq-cov-test-setup "coverage_stats.csv")
       (assoc "/path/to/app/init.js" (tq-cov-parse-buffer (current-buffer)))
       ))
   (expect '("/path/to/app/init.js" 8 8 6 4)
     (with-current-buffer (tq-cov-test-setup "coverage_stats2.csv")
       (assoc "/path/to/app/init.js" (tq-cov-parse-buffer (current-buffer)))
       ))
   (expect '("/path/to/lib/utils.js" 82 82 76 76 70 70 62 62 55 55 38 37 29 27 24 22 17 17 6 4)
     (with-current-buffer (tq-cov-test-setup "coverage_stats3.csv")
       (assoc "/path/to/lib/utils.js" (tq-cov-parse-buffer (current-buffer)))
       ))
   (expect '("/path/to/app/init.js" 20 19)
     (with-current-buffer (tq-cov-test-setup "coverage_stats4.csv")
       (assoc "/path/to/app/init.js" (tq-cov-parse-buffer (current-buffer)))
       ))
   (expect '("/path/to/lib/utils.js" 82 82 76 76 70 70 62 62 55 55 38 37 29 27 24 22 17 17 6 4)
     (with-current-buffer (tq-cov-test-setup "coverage_stats4.csv")
       (assoc "/path/to/lib/utils.js" (tq-cov-parse-buffer (current-buffer)))
       ))

   (desc "tq-cov-create-tuple-pairs")
   (expect '(("foo" "bar") ("baz" "hoge"))
     (tq-cov-create-tuple-pairs '("foo" "bar" "baz" "hoge")))
   (expect '(("foo" "bar") ("baz" "hoge") ("fuga" nil))
     (tq-cov-create-tuple-pairs '("foo" "bar" "baz" "hoge" "fuga")))

   (desc "tq-cov-reverse-cdr-of-alist")
   (expect '("Japanese" . ("piyo" "fuga" "hoge"))
     (setq words '(("Japanese" . ("hoge" "fuga" "piyo")) ("English" . ("foo" "bar" "baz"))))
     (assoc "Japanese" (tq-cov-reverse-cdr-of-alist words))
     )
   (expect '("English" . ("baz" "bar" "foo"))
     (setq words '(("Japanese" . ("hoge" "fuga" "piyo")) ("English" . ("foo" "bar" "baz"))))
     (assoc "English" (tq-cov-reverse-cdr-of-alist words))
     )
   (expect '("/path/to/app/init.js" 4 6 8 8)
     (with-current-buffer (tq-cov-test-setup "coverage_stats2.csv")
       (setq rev-alist (tq-cov-reverse-cdr-of-alist (tq-cov-parse-buffer (current-buffer))))
       (assoc "/path/to/app/init.js" rev-alist)
       ))

   (desc "tq-cov-tuplize-cdr-of-alist")
   (expect '("Japanese" . (("hoge" "fuga") ("piyo" "moge")))
     (setq words '(("Japanese" . ("hoge" "fuga" "piyo" "moge")) ("English" . ("foo" "bar" "baz" "moo"))))
     (assoc "Japanese" (tq-cov-tuplize-cdr-of-alist words))
     )
   (expect '("English" . (("foo" "bar") ("baz" "moo")))
     (setq words '(("Japanese" . ("hoge" "fuga" "piyo" "moge")) ("English" . ("foo" "bar" "baz" "moo"))))
     (assoc "English" (tq-cov-tuplize-cdr-of-alist words))
     )


   (desc "tq-cov-create-stats-alist-from-buffer")
   (expect '((4 6) (17 17) (22 24) (27 29) (37 38) (55 55) (62 62) (70 70) (76 76) (82 82))
     (setq stats-buf (tq-cov-test-setup "coverage_stats4.csv"))
     (setq stats-alist (tq-cov-create-stats-alist-from-buffer stats-buf))
     (cdr (assoc "/path/to/lib/utils.js" stats-alist)))
   (expect '((19 20))
     (setq stats-buf (tq-cov-test-setup "coverage_stats4.csv"))
     (setq stats-alist (tq-cov-create-stats-alist-from-buffer stats-buf))
     (cdr (assoc "/path/to/app/init.js" stats-alist)))

   (desc "tq-cov-create-stats-alist-from-buffer bug reproduction")
   (expect '((4 6) (17 17) (22 24) (27 29) (37 38) (55 55) (62 62) (70 70) (76 76) (82 82))
     (setq stats-buf (tq-cov-test-setup "coverage_stats4_reverse.csv"))
     (setq stats-alist (tq-cov-create-stats-alist-from-buffer stats-buf))
     (cdr (assoc "/path/to/lib/utils.js" stats-alist)))
   (expect '((19 20))
     (setq stats-buf (tq-cov-test-setup "coverage_stats4_reverse.csv"))
     (setq stats-alist (tq-cov-create-stats-alist-from-buffer stats-buf))
     (cdr (assoc "/path/to/app/init.js" stats-alist)))

   (desc "large data")
   (expect '((2 2) (80 80) (95 95) (203 204) (210 211) (217 222) (224 224) (226 226) (235 238) (245 245) (250 255) (290 290)  (300 303) (305 310) (360 360))
     (setq stats-buf (tq-cov-test-setup "coverage_stats_large.csv"))
     (setq stats-alist (tq-cov-create-stats-alist-from-buffer stats-buf))
     (cdr (assoc "/path/to/app/Util.js" stats-alist)))


   )
